import { Workflow, Tag } from './types';

export const mockWorkflows: Workflow[] = [
  {
    id: '1',
    title: 'Advanced Email Marketing Automation',
    category: 'Marketing',
    rating: 4.8,
    description: 'Complete email marketing workflow with segmentation, A/B testing, and analytics integration.',
    tags: ['Email Marketing', 'Analytics', 'Automation'],
    benefits: ['Segmentation', 'A/B Testing', 'Analytics'],
    downloads: 1250,
    price: 49,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '15 min',
    featured: true
  },
  {
    id: '2',
    title: 'CRM Data Synchronization',
    category: 'CRM',
    rating: 4.9,
    description: 'Sync customer data between multiple CRM systems with real-time updates and conflict resolution.',
    tags: ['CRM Integration', 'Data Sync', 'Automation'],
    benefits: ['Real-time Sync', 'Conflict Resolution', 'Multi-system'],
    downloads: 890,
    price: 79,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '20 min'
  },
  {
    id: '3',
    title: 'Social Media Content Scheduler',
    category: 'Social Media',
    rating: 4.7,
    description: 'Automate social media posting across multiple platforms with content optimization and scheduling.',
    tags: ['Social Media', 'Content Management', 'Scheduling'],
    benefits: ['Multi-platform', 'Content Optimization', 'Scheduling'],
    downloads: 2100,
    price: 35,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '10 min'
  },
  {
    id: '4',
    title: 'E-commerce Order Processing',
    category: 'E-commerce',
    rating: 4.6,
    description: 'Complete order fulfillment workflow with inventory management and customer notifications.',
    tags: ['E-commerce', 'Order Processing', 'Inventory'],
    benefits: ['Order Fulfillment', 'Inventory Management', 'Notifications'],
    downloads: 1650,
    price: 65,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '25 min'
  },
  {
    id: '5',
    title: 'Financial Reporting Dashboard',
    category: 'Finance',
    rating: 4.9,
    description: 'Automated financial reporting with data visualization and scheduled report generation.',
    tags: ['Finance', 'Reporting', 'Analytics'],
    benefits: ['Data Visualization', 'Scheduled Reports', 'Analytics'],
    downloads: 750,
    price: 95,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '30 min'
  },
  {
    id: '6',
    title: 'Customer Support Ticket Routing',
    category: 'Customer Support',
    rating: 4.5,
    description: 'Intelligent ticket routing based on priority, department, and customer history.',
    tags: ['Customer Support', 'Ticket Management', 'Automation'],
    benefits: ['Intelligent Routing', 'Priority Management', 'History Tracking'],
    downloads: 1200,
    price: 45,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '18 min'
  },
  {
    id: '7',
    title: 'Lead Generation & Qualification',
    category: 'Sales',
    rating: 4.8,
    description: 'Automated lead capture, scoring, and qualification with CRM integration.',
    tags: ['Lead Generation', 'Sales', 'CRM Integration'],
    benefits: ['Lead Capture', 'Scoring', 'CRM Integration'],
    downloads: 1800,
    price: 55,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '22 min'
  },
  {
    id: '8',
    title: 'Inventory Management System',
    category: 'Inventory',
    rating: 4.4,
    description: 'Real-time inventory tracking with low-stock alerts and automated reordering.',
    tags: ['Inventory', 'Management', 'Alerts'],
    benefits: ['Real-time Tracking', 'Low-stock Alerts', 'Auto-reordering'],
    downloads: 950,
    price: 40,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '15 min'
  },
  {
    id: '9',
    title: 'API Integration Hub',
    category: 'Integration',
    rating: 4.7,
    description: 'Centralized API management with data transformation and error handling.',
    tags: ['API Integration', 'Data Transformation', 'Automation'],
    benefits: ['Centralized Management', 'Data Transformation', 'Error Handling'],
    downloads: 1100,
    price: 85,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '35 min'
  },
  {
    id: '10',
    title: 'Notification Center',
    category: 'Notifications',
    rating: 4.6,
    description: 'Multi-channel notification system with templates and delivery tracking.',
    tags: ['Notifications', 'Multi-channel', 'Templates'],
    benefits: ['Multi-channel', 'Templates', 'Delivery Tracking'],
    downloads: 1400,
    price: 30,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '12 min'
  },
  {
    id: '11',
    title: 'Data Analytics Pipeline',
    category: 'Analytics',
    rating: 4.9,
    description: 'End-to-end data processing pipeline with visualization and insights generation.',
    tags: ['Analytics', 'Data Processing', 'Visualization'],
    benefits: ['End-to-end Pipeline', 'Data Processing', 'Insights Generation'],
    downloads: 800,
    price: 120,
    image: ['/background1.png'],
    author: 'UsITech Team',
    timeToSetup: '40 min'
  },
  {
    id: '12',
    title: 'Workflow Monitoring Dashboard',
    category: 'Monitoring',
    rating: 4.5,
    description: 'Real-time monitoring and alerting for all your automation workflows.',
    tags: ['Monitoring', 'Dashboard', 'Alerts'],
    benefits: ['Real-time Monitoring', 'Dashboard', 'Alerts'],
    downloads: 650,
    price: 70,
    image: ['/workflow-12.jpg'],
    author: 'UsITech Team',
    timeToSetup: '20 min'
  }
];

export const popularTags: Tag[] = [
  { id: 'email-marketing', name: 'Email Marketing', count: 8 },
  { id: 'crm-integration', name: 'CRM Integration', count: 12 },
  { id: 'social-media', name: 'Social Media', count: 15 },
  { id: 'e-commerce', name: 'E-commerce', count: 9 },
  { id: 'analytics', name: 'Analytics', count: 11 },
  { id: 'automation', name: 'Automation', count: 20 },
  { id: 'data-sync', name: 'Data Sync', count: 7 },
  { id: 'reporting', name: 'Reporting', count: 6 },
  { id: 'customer-support', name: 'Customer Support', count: 5 },
  { id: 'finance', name: 'Finance', count: 4 },
  { id: 'inventory', name: 'Inventory', count: 3 },
  { id: 'lead-generation', name: 'Lead Generation', count: 8 },
  { id: 'notifications', name: 'Notifications', count: 10 },
  { id: 'api-integration', name: 'API Integration', count: 14 }
];
