import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../lib/contexts/AuthContext";
import { UserProvider } from "../lib/contexts/UserContext";
import { WorkflowProvider } from "../lib/contexts/WorkflowContext";
import { WishlistProvider } from "../lib/contexts/WishlistContext";
import { WalletProvider } from "../lib/contexts/WalletContext";
import AutoRefreshToken from "../components/shared/AutoRefreshToken";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <UserProvider>
            <WorkflowProvider>
              <WishlistProvider>
                <WalletProvider>
                  <AutoRefreshToken />
                  {children}
                </WalletProvider>
              </WishlistProvider>
            </WorkflowProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
